### ISSUE TITLE
Instagram user missing properties

### ISSUE THREAD

**Issue by madashio** [SocialBlade/socialblade-js#14]
Instagram user interface is missing `statistics.growth` and `statistics.average` 

Library Version: 1.0.4

Node Version: 18.13.0

**Comment by timcole** [comment]
Thank you for the heads up! We will get this added in the week (probably Monday). If you need it sooner feel free to open a PR with the change.

**Comment by madashio** [comment]
Take your time. I'm not in that big of a rush, enjoy your weekend

**Comment by madashio** [comment]
Also Facebook user is missing `statistics.growth.likes` and `statistics.growth.talking_about`

**Comment by madashio** [comment]
Also Twitter user is missing `statistics.growth.followers` and `statistics.growth.tweets`
