### ISSUE TITLE
Odysee is not available

### ISSUE THREAD

**Issue by dario13** [SocialBlade/socialblade-js#19]
Hi! I saw on the docs that you added Odysee as a new platform, but it's not available as part of this library yet. 

Do you have some estimation on when Odysee will be available?

Thanks!

**Comment by timcole** [comment]
Hello,

Thanks for bringing it to our attention that Odysee wasn't added to the SDK even though it's accessible via our business API. As we’re currently rebuilding our systems from the ground up, we’re also re-evaluating platform support, particularly for those with lower performance. At this time, Odysee isn’t planned for addition to the SDK, but we’ll continue to consider community feedback as we assess our platform lineup.

Thank you again, and let us know if there’s anything else we can help with!
