### ISSUE TITLE
Country specific data 

### ISSUE THREAD

**Issue by mark1282** [SocialBlade/socialblade-js#4]
Hi I'm trying to pull back top youtubers. I was wondering if there is a way to get country specific date. Say top 100 YouTubers in the UK?

## Information

Library Version:

Node Version: 

---

**Comment by timcole** [comment]
At this time we do not support filtering by country in our API. However, you can see this information on [our website](https://socialblade.com/youtube/top/country/gb) directly, or if you need more than that you can purchase a [custom report](https://socialblade.com/reports).

If you have any more questions about this feel free to [contact our support](https://support.socialblade.com/) who will be more than happy to help further.
