### ISSUE TITLE
Insgram not available on NPM package

### ISSUE THREAD

**Issue by Macelai** [SocialBlade/socialblade-js#9]
Library Version: 1.0.0

## Description (Include examples and logs if relevant)

Hey, thanks for this amazing SDK, I was testing it to use on my app, and I can see that there is Instagram support but there is not released version on NPM to use it

**Comment by timcole** [comment]
Good catch! Sorry, this update never made it out to npm, Actions show that it passed successfully so should have been published but sadly the logs expired so I can't see what happened. I'll get his published manually for you soon!

**Comment by timcole** [comment]
1.0.1 should now be published on npm! Sorry again for the trouble.
